.job_template: &deployer
  stage: deploy
  tags:
    - phpmw
    - server

stages:
  - deploy

deploy_production:
  <<: *deployer
  script:
    - "cp /tmp/deploy.php ."
    - "php bin/dep deploy production"
  only:
    - master
