version: '2'
services:
  php:
    dns: 8.8.8.8
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    networks:
      - base
  redis:
    image: redis:3-alpine
    networks:
      - base
networks:
  base:
