version: '2'
services:
  php:
    dns: 8.8.8.8
    build: ./docker
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    networks:
      - base
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=mvlabs
      - POSTGRES_PASSWORD=mvlabs
      - POSTGRES_DB=mvlabs
    networks:
      - base
    ports:
      - 5432:5432
#  phppgadmin:
#    image: maxexcloo/phppgadmin
#    networks:
#      - base
#    links:
#      - postgres:postgresql
#    ports:
#      - 8080:80
networks:
  base:
